# Generated by Django 5.1.5 on 2025-01-22 12:56

import apps.books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=128, verbose_name='Author full name')),
                ('name', models.CharField(max_length=248, verbose_name='Book name')),
                ('audio', models.FileField(upload_to='files/audios/', validators=[apps.books.models.validate_mp3], verbose_name='Audio book')),
                ('book', models.FileField(upload_to='files/books/', validators=[apps.books.models.validate_pdf], verbose_name='book')),
            ],
        ),
    ]
