# Generated by Django 5.1.5 on 2025-01-28 16:06

import apps.books.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=128, verbose_name='Author full name')),
                ('name', models.CharField(max_length=248, verbose_name='Book name')),
                ('audio', models.FileField(upload_to='files/audios/', validators=[apps.books.models.validate_mp3], verbose_name='Audio book')),
                ('book', models.FileField(upload_to='files/books/', validators=[apps.books.models.validate_pdf], verbose_name='book')),
            ],
        ),
        migrations.CreateModel(
            name='Books_population',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(verbose_name='Telegram user id')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_entries', to='books.books', verbose_name='Book_id')),
            ],
        ),
    ]
