# Generated by Django 5.1.5 on 2025-01-29 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_books_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='Books description'),
        ),
        migrations.AlterField(
            model_name='books',
            name='name',
            field=models.CharField(max_length=248, verbose_name='Book name'),
        ),
    ]
